CREATE TABLE IF NOT EXISTS users
(
    id       bigint generated by default as identity primary key,
    email    text    not null,
    password text    not null,
    enabled  boolean not null default true,
    CONSTRAINT users_email_uix UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    id      bigint generated by default as identity primary key,
    name    varchar(20) not null,
    user_id bigint      not null,
    constraint user_fk foreign key (user_id) references users (id)
);